server:
  port: 9000

spring:
  # 配置MySQL数据库的连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.9.96:3307/springboot?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=CTT
    username: root
    password: 123456

    tomcat:
      max-active: 20
      max-idle: 10
      initial-size: 5
      max-wait: 10000
      # 采用隔离级别为读写提交
      default-transaction-isolation: 2

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  redis:
    host: 172.16.9.96
    port: 6888
    database: 2
    timeout: 10s
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 2000ms

# mybatis的相关配置
mybatis:
  type-aliases-package: com.springboot.chapter15.pojo
  mapper-locations: classpath:/mapper/*.xml